title: Ricardo Zacarias
author: Ricardo Zacarias
description: > 
  My personal data playground.
show_excerpts: true 

sass:
  sass_dir: _sass
plainwhite:
  name: Ricardo Zacarias
  tagline: Data Stories
  date_format: "%b %-d, %Y"
  sitemap: false
  analytics_id: "UA-164344589-1"

  navigation:
    - title: Stories
      url: "/#posts-label"
    - title: About
      url: "/about"

  social_links:
    github:  ricardozacarias
    linkedIn: in/ricardo-zacarias
    rss: rss

# Build settings
remote_theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed