# User config
author: "Ricardo Zacarias"
tagline: "Data"
description: "Hi I'm Ricardo. I like to tell stories from numbers and this is my playground."
keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "hi@ricardozacarias.com"
linkedin: "https://www.linkedin.com/in/ricardo-zacarias/"
github: "https://github.com/ricardozacarias"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed