# User config
author: "Pineapple"
tagline: "Pineapple Certfied Jekyll Theme"
description: "A neuroscientist "
email: "pineapple@example.com"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
baseurl: "/pineapple"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
