title: ricardozacarias.com
author: Ricardo Zacarias
email: alex@alexandermussell.com
description: > 
  My personal data playground.
show_excerpts: true 

sass:
  sass_dir: _sass
plainwhite:
  name: Ricardo Zacarias
  tagline: Data, Neuroscience
  date_format: "%b %-d, %Y"
  sitemap: false
  analytics_id: "UA-164344589-1"

  navigation:
    - title: Home
      url: "/"
    - title: About
      url: "/about"

  social_links:
    github:  ricardozacarias
    linkedIn: in/thelehhman
    rss: rss

# Build settings
remote_theme: plainwhite

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
